// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather.Infra.Data;

namespace Weather.Infra.Migrations
{
    [DbContext(typeof(OpenWeatherContext))]
    [Migration("20210127163323_CreateTableHistoricWeather")]
    partial class CreateTableHistoricWeather
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Weather.Domain.Models.HistoricWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Timezone")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TimezoneOffset")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistoricWeather");
                });

            modelBuilder.Entity("Weather.Domain.Models.HistoricWeatherDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Clouds")
                        .HasColumnType("int");

                    b.Property<double>("DewPoint")
                        .HasColumnType("float");

                    b.Property<int>("Dt")
                        .HasColumnType("int");

                    b.Property<Guid>("HistoricWeatherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<double>("Pop")
                        .HasColumnType("float");

                    b.Property<int>("Pressure")
                        .HasColumnType("int");

                    b.Property<double>("Rain")
                        .HasColumnType("float");

                    b.Property<int>("Sunrise")
                        .HasColumnType("int");

                    b.Property<int>("Sunset")
                        .HasColumnType("int");

                    b.Property<double>("Uvi")
                        .HasColumnType("float");

                    b.Property<int>("WindDeg")
                        .HasColumnType("int");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("HistoricWeatherId");

                    b.ToTable("HistoricWeatherDaily");
                });

            modelBuilder.Entity("Weather.Domain.Models.OpenWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Cod")
                        .HasColumnType("int");

                    b.Property<int>("Dt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Timezone")
                        .HasColumnType("int");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OpenWeather");
                });

            modelBuilder.Entity("Weather.Domain.Models.HistoricWeatherDaily", b =>
                {
                    b.HasOne("Weather.Domain.Models.HistoricWeather", "HistoricWeather")
                        .WithMany("Daily")
                        .HasForeignKey("HistoricWeatherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Weather.Domain.Models.HistoricTemp", "Temp", b1 =>
                        {
                            b1.Property<Guid>("HistoricWeatherDailyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Day")
                                .HasColumnName("Day")
                                .HasColumnType("float");

                            b1.Property<double>("Eve")
                                .HasColumnName("Eve")
                                .HasColumnType("float");

                            b1.Property<double>("Max")
                                .HasColumnName("Max")
                                .HasColumnType("float");

                            b1.Property<double>("Min")
                                .HasColumnType("float");

                            b1.Property<double>("Morn")
                                .HasColumnName("Morn")
                                .HasColumnType("float");

                            b1.Property<double>("Night")
                                .HasColumnName("Night")
                                .HasColumnType("float");

                            b1.HasKey("HistoricWeatherDailyId");

                            b1.ToTable("HistoricWeatherDaily");

                            b1.WithOwner()
                                .HasForeignKey("HistoricWeatherDailyId");
                        });
                });

            modelBuilder.Entity("Weather.Domain.Models.OpenWeather", b =>
                {
                    b.OwnsOne("Weather.Domain.Models.OpenWeatherCoordinate", "Coord", b1 =>
                        {
                            b1.Property<Guid>("OpenWeatherId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Lat")
                                .HasColumnName("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Lon")
                                .HasColumnName("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("OpenWeatherId");

                            b1.ToTable("OpenWeather");

                            b1.WithOwner()
                                .HasForeignKey("OpenWeatherId");
                        });

                    b.OwnsOne("Weather.Domain.Models.OpenWeatherMain", "Main", b1 =>
                        {
                            b1.Property<Guid>("OpenWeatherId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("FeelsLike")
                                .HasColumnName("FeelsLike")
                                .HasColumnType("float");

                            b1.Property<double>("Humidity")
                                .HasColumnName("Humidity")
                                .HasColumnType("float");

                            b1.Property<double>("Pressure")
                                .HasColumnName("Pressure")
                                .HasColumnType("float");

                            b1.Property<double>("Temp")
                                .HasColumnName("Temp")
                                .HasColumnType("float");

                            b1.Property<double>("TempMax")
                                .HasColumnName("TempMax")
                                .HasColumnType("float");

                            b1.Property<double>("TempMin")
                                .HasColumnName("TempMin")
                                .HasColumnType("float");

                            b1.HasKey("OpenWeatherId");

                            b1.ToTable("OpenWeather");

                            b1.WithOwner()
                                .HasForeignKey("OpenWeatherId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
